name: Kingdoms
version: '${project.version}'
main: de.kuscheltiermafia.kingdoms.Main
api-version: '1.21'
commands:
  itemlist:
    description: List all items in the Kingdoms plugin
    usage: /itemlist
