name: Kingdoms
version: '${project.version}'
main: de.kuscheltiermafia.kingdoms.Kingdoms
api-version: '1.21'
commands:
  itemlist:
    description: List all items in the Kingdoms plugin
  getstats:
    description: Get the stats of a player